#### git main 브랜치에 push가 일어났을때 travis가 해야할 일들을 기술함.

sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t ssw0418/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true ssw0418/docker-react-app npm run test -- --coverage
# -e CI=true 는 없으면 travis에서 오류가 나기 때문.  --coverage 는 로그를 상세하게 보기 위함.

deploy: 
  provider: "elasticbeanstalk"  #외부 서비스 표시(s3, elasticbeanstalk, firebase 등등)
  region: "ap-northeast-2" # 현재 사용하고 있는 AWS의 서비스가 위치하고 있는 물리적 장소
  app: "docker-react-app" #생성된 어플리케이션의 이름
  env: "Dockerreactapp-env" 
  bucket_name: "elasticbeanstalk-ap-northeast-2-031911139728" # 해당 elasticbeanstalk을 위한 s3 버켓 이름
  bucket_path: "docker-react-app" #어플리케이션 이름과 동일
  on:
    branch: master #어떤 브랜치에 Push를 할때 AWS에 배포를 할 것인지.

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY