version: '3'  #도커 컴포즈의 버전
services: #실행할 컨테이너들을 정의
  react:  #컨테이너 이름
    build:  # 현 디렉토리에 있는 Docker 사용
      context: .  #도커 이미지를 구성하기 위한 파일과 폴더들이 있는 위치
      dockerfile: Dockerfile.dev   #어떤 도커 파일 사용할지 지정 -f
    ports:  #포트매핑  로컬포트 : 컨테이너포트 -p
      - "3000:3000"
    volumes:     #로컬 머신에 있는 파일들 매핑 -v
      - /usr/src/app/node_modules
      - ./:/usr/src/app 
    stdin_open: true #리액트 앱을 끌때 필요(버그 수정)
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm", "run", "test"]